# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2018-02-18 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='gunit',
            field=models.CharField(default='500g', max_length=20),
        ),
    ]
